/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankOfDioAditya;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dio Aditya Putra Wardhono
 */
public class Account extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        autoAccountID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private Connection conn;
    private PreparedStatement insert;
    private ResultSet rs;

    /**
     *
     */
    public void autoAccountID() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            Statement stmt = getConn().createStatement();

            setRs(stmt.executeQuery(
                    "select MAX(account_id) from account"
            ));
            getRs().next();
            getRs().getString("Max(account_id)");

            if (getRs().getString("Max(account_id)") == null) {

                AccountNoValue.setText("A001");

            } else {

                long id = Long.parseLong(getRs().getString("Max(account_id)").substring(2, getRs().getString("Max(account_id)").length()
                )
                );
                id++;

                AccountNoValue.setText("A" + String.format("%03d", id));

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        AccountPanel = new javax.swing.JPanel();
        AccountNoLabel = new javax.swing.JLabel();
        CustomerIDLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        AccountTypeLabel = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        CustomerIDTextField = new javax.swing.JTextField();
        BalanceTextField = new javax.swing.JTextField();
        AccountNoValue = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        AccountTypeComboBox = new javax.swing.JComboBox<>();
        FindButton = new javax.swing.JButton();
        CustomerNameValue = new javax.swing.JLabel();
        AccountTitleLabel = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        AccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));

        AccountNoLabel.setText("Account No.");

        CustomerIDLabel.setText("Customer ID");

        CustomerNameLabel.setText("Customer Name");

        AccountTypeLabel.setText("Account Type");

        BalanceLabel.setText("Balance");

        AccountNoValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountNoValue.setForeground(new java.awt.Color(51, 102, 255));
        AccountNoValue.setText("jLabel9");

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        AccountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Fix", "Current" }));

        FindButton.setText("Find");
        FindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonActionPerformed(evt);
            }
        });

        CustomerNameValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerNameValue.setForeground(new java.awt.Color(51, 102, 255));
        CustomerNameValue.setText("jLabel1");

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountNoLabel)
                    .addComponent(CustomerIDLabel)
                    .addComponent(CustomerNameLabel)
                    .addComponent(AccountTypeLabel)
                    .addComponent(BalanceLabel))
                .addGap(64, 64, 64)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AccountPanelLayout.createSequentialGroup()
                                .addComponent(AddButton)
                                .addGap(18, 18, 18)
                                .addComponent(CancelButton))
                            .addComponent(CustomerIDTextField)
                            .addComponent(BalanceTextField)
                            .addComponent(AccountNoValue)
                            .addComponent(AccountTypeComboBox, 0, 256, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(FindButton))
                    .addComponent(CustomerNameValue))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNoLabel)
                    .addComponent(AccountNoValue))
                .addGap(34, 34, 34)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIDLabel)
                    .addComponent(CustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindButton))
                .addGap(35, 35, 35)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameValue))
                .addGap(34, 34, 34)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountTypeLabel)
                    .addComponent(AccountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CancelButton))
                .addGap(14, 14, 14))
        );

        AccountTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AccountTitleLabel.setText("Bank of Dio Aditya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountTitleLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(AccountTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            // TODO add your handling code here:
            String account_id = AccountNoValue.getText();
            String customer_id = CustomerIDTextField.getText();
            String balance = BalanceTextField.getText();
            String account_type = AccountTypeComboBox.getSelectedItem().toString();

            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            setInsert(getConn().prepareStatement(
                    "insert into account(account_id,customer_id"
                    + ",account_type,balance)values(?,?,?,?)"
            ));
            getInsert().setString(1, account_id);
            getInsert().setString(2, customer_id);
            getInsert().setString(3, account_type);
            getInsert().setString(4, balance);
            getInsert().executeUpdate();

            JOptionPane.showMessageDialog(this, "New Account Added");

            // AccountNoValue.setText("");
            CustomerIDTextField.setText("");
            CustomerNameValue.setText("");
            AccountTypeComboBox.setSelectedIndex(-1);
            BalanceTextField.setText("");

            autoAccountID();

            CustomerIDTextField.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
        try {
            // TODO add your handling code here:
            String customer_id = CustomerIDTextField.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            setInsert(getConn().prepareStatement("select * from customer where customer_id = ?"));
            getInsert().setString(1, customer_id);
            setRs(getInsert().executeQuery());

            if (getRs().next() == false) {
                JOptionPane.showMessageDialog(this, "Customer not Found");
            } else {
                String firstname = getRs().getString("firstname");
                CustomerNameValue.setText(firstname.trim());
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_FindButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNoLabel;
    private javax.swing.JLabel AccountNoValue;
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JLabel AccountTitleLabel;
    private javax.swing.JComboBox<String> AccountTypeComboBox;
    private javax.swing.JLabel AccountTypeLabel;
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JTextField BalanceTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CustomerIDLabel;
    private javax.swing.JTextField CustomerIDTextField;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel CustomerNameValue;
    private javax.swing.JButton FindButton;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the rs
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * @param rs the rs to set
     */
    public void setRs(ResultSet rs) {
        this.rs = rs;
    }

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }

    /**
     * @param conn the conn to set
     */
    public void setConn(Connection conn) {
        this.conn = conn;
    }

    /**
     * @return the insert
     */
    public PreparedStatement getInsert() {
        return insert;
    }

    /**
     * @param insert the insert to set
     */
    public void setInsert(PreparedStatement insert) {
        this.insert = insert;
    }
}
