/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankOfDioAditya;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dio Aditya Putra Wardhono
 */
public class Customer extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        autoCustomerID();
        branch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private Connection conn;
    private PreparedStatement insert;
    private ResultSet rs;

    /**
     *
     */
    public void autoCustomerID() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            Statement stmt = getConn().createStatement();

            setRs(stmt.executeQuery("select MAX(customer_id) from customer"));
            getRs().next();
            getRs().getString("Max(customer_id)");

            if (getRs().getString("Max(customer_id)") == null) {

                CustomerNoValue.setText("CS001");

            } else {

                long id = Long.parseLong(getRs().getString("Max(customer_id)").substring(2, getRs().getString("Max(customer_id)").length()
                )
                );
                id++;

                CustomerNoValue.setText("CS" + String.format("%03d", id));

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }

    }

    /**
     *
     */
    public void branch() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            setInsert(getConn().prepareStatement("select * from branch"));
            setRs(getInsert().executeQuery());
            BranchComboBox.removeAllItems();

            while (getRs().next()) {
                BranchComboBox.addItem(getRs().getString(2));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        AccountPanel = new javax.swing.JPanel();
        CustomerNoLabel = new javax.swing.JLabel();
        FirstnameLabel = new javax.swing.JLabel();
        LastnameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        BranchLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        CityTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        CustomerNoValue = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        BranchComboBox = new javax.swing.JComboBox<>();
        CustomerTitleLabel = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        AccountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer"));

        CustomerNoLabel.setText("Customer No.");

        FirstnameLabel.setText("First Name");

        LastnameLabel.setText("Last Name");

        AddressLabel.setText("Address");

        CityLabel.setText("City");

        BranchLabel.setText("Branch");

        PhoneLabel.setText("Phone No.");

        CustomerNoValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerNoValue.setForeground(new java.awt.Color(51, 102, 255));
        CustomerNoValue.setText("jLabel9");

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerNoLabel)
                    .addComponent(FirstnameLabel)
                    .addComponent(LastnameLabel)
                    .addComponent(AddressLabel)
                    .addComponent(CityLabel)
                    .addComponent(BranchLabel)
                    .addComponent(PhoneLabel))
                .addGap(64, 64, 64)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AccountPanelLayout.createSequentialGroup()
                        .addComponent(AddButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton))
                    .addComponent(FirstNameTextField)
                    .addComponent(LastNameTextField)
                    .addComponent(AddressTextField)
                    .addComponent(CityTextField)
                    .addComponent(PhoneTextField)
                    .addComponent(CustomerNoValue)
                    .addComponent(BranchComboBox, 0, 256, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNoLabel)
                    .addComponent(CustomerNoValue))
                .addGap(34, 34, 34)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstnameLabel)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameLabel)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLabel))
                .addGap(31, 31, 31)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BranchLabel)
                    .addComponent(BranchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(CancelButton))
                .addGap(14, 14, 14))
        );

        CustomerTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CustomerTitleLabel.setText("Bank of Dio Aditya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerTitleLabel))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CustomerTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        try {
            // TODO add your handling code here:
            String customer_id = CustomerNoValue.getText();
            String first_name = FirstNameTextField.getText();
            String last_name = LastNameTextField.getText();
            String address = AddressTextField.getText();
            String city = CityTextField.getText();
            String branch = BranchComboBox.getSelectedItem().toString();
            String phone_number = PhoneTextField.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", "")
            );
            setInsert(getConn().prepareStatement(
                    "insert into customer"
                    + "(customer_id,firstname,lastname,"
                    + "address,city,branch,phone_number)values(?,?,?,?,?,?,?)"
            ));
            getInsert().setString(1, customer_id);
            getInsert().setString(2, first_name);
            getInsert().setString(3, last_name);
            getInsert().setString(4, address);
            getInsert().setString(5, city);
            getInsert().setString(6, branch);
            getInsert().setString(7, phone_number);
            getInsert().executeUpdate();

            JOptionPane.showMessageDialog(this, "New Customer Added");

            //CustomerNoValue.setText("");
            FirstNameTextField.setText("");
            LastNameTextField.setText("");
            AddressTextField.setText("");
            CityTextField.setText("");
            BranchComboBox.setSelectedIndex(-1);
            PhoneTextField.setText("");

            autoCustomerID();

            FirstNameTextField.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }

    }//GEN-LAST:event_AddButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JComboBox<String> BranchComboBox;
    private javax.swing.JLabel BranchLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JLabel CustomerNoLabel;
    private javax.swing.JLabel CustomerNoValue;
    private javax.swing.JLabel CustomerTitleLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel LastnameLabel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }

    /**
     * @param conn the conn to set
     */
    public void setConn(Connection conn) {
        this.conn = conn;
    }

    /**
     * @return the insert
     */
    public PreparedStatement getInsert() {
        return insert;
    }

    /**
     * @param insert the insert to set
     */
    public void setInsert(PreparedStatement insert) {
        this.insert = insert;
    }

    /**
     * @return the rs
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * @param rs the rs to set
     */
    public void setRs(ResultSet rs) {
        this.rs = rs;
    }

}
