/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankOfDioAditya;

/**
 *
 * @author Dio Aditya Putra Wardhono
 */
public class MainMenu extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDesktop = new javax.swing.JDesktopPane();
        MainDesktopMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        CustomerMenu = new javax.swing.JMenuItem();
        AccountFileMenu = new javax.swing.JMenuItem();
        TransactionMenu = new javax.swing.JMenu();
        DepositMenu = new javax.swing.JMenuItem();
        WithdrawMenu = new javax.swing.JMenuItem();
        TransferMenu = new javax.swing.JMenu();
        AcctoAccMenu = new javax.swing.JMenuItem();
        ReportMenu = new javax.swing.JMenu();
        CustomerReportMenu = new javax.swing.JMenuItem();
        BalanceMenu = new javax.swing.JMenu();
        CheckBalanceMenu = new javax.swing.JMenuItem();
        AccountMenu = new javax.swing.JMenu();
        UserAccountMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        MainDesktop.setToolTipText("");
        MainDesktop.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout MainDesktopLayout = new javax.swing.GroupLayout(MainDesktop);
        MainDesktop.setLayout(MainDesktopLayout);
        MainDesktopLayout.setHorizontalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        MainDesktopLayout.setVerticalGroup(
            MainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        FileMenu.setText("File");

        CustomerMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CustomerMenu.setText("Customer");
        CustomerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuActionPerformed(evt);
            }
        });
        FileMenu.add(CustomerMenu);

        AccountFileMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AccountFileMenu.setText("Account");
        AccountFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountFileMenuActionPerformed(evt);
            }
        });
        FileMenu.add(AccountFileMenu);

        MainDesktopMenuBar.add(FileMenu);

        TransactionMenu.setText("Transaction");

        DepositMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DepositMenu.setText("Deposit");
        DepositMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositMenuActionPerformed(evt);
            }
        });
        TransactionMenu.add(DepositMenu);

        WithdrawMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        WithdrawMenu.setText("Withdraw");
        WithdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawMenuActionPerformed(evt);
            }
        });
        TransactionMenu.add(WithdrawMenu);

        MainDesktopMenuBar.add(TransactionMenu);

        TransferMenu.setText("Transfer");

        AcctoAccMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        AcctoAccMenu.setText("Account to Account");
        AcctoAccMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcctoAccMenuActionPerformed(evt);
            }
        });
        TransferMenu.add(AcctoAccMenu);

        MainDesktopMenuBar.add(TransferMenu);

        ReportMenu.setText("Report");

        CustomerReportMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CustomerReportMenu.setText("Customer Report");
        CustomerReportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerReportMenuActionPerformed(evt);
            }
        });
        ReportMenu.add(CustomerReportMenu);

        MainDesktopMenuBar.add(ReportMenu);

        BalanceMenu.setText("Balance");

        CheckBalanceMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CheckBalanceMenu.setText("Check Balance");
        CheckBalanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBalanceMenuActionPerformed(evt);
            }
        });
        BalanceMenu.add(CheckBalanceMenu);

        MainDesktopMenuBar.add(BalanceMenu);

        AccountMenu.setText("Account");

        UserAccountMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UserAccountMenu.setText("User Account");
        UserAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserAccountMenuActionPerformed(evt);
            }
        });
        AccountMenu.add(UserAccountMenu);

        MainDesktopMenuBar.add(AccountMenu);

        setJMenuBar(MainDesktopMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuActionPerformed
        // TODO add your handling code here:
        Customer cust;
        cust = new Customer();

        MainDesktop.add(cust);
        cust.setVisible(true);
    }//GEN-LAST:event_CustomerMenuActionPerformed

    private void AccountFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountFileMenuActionPerformed
        // TODO add your handling code here:
        Account acc;
        acc = new Account();

        MainDesktop.add(acc);
        acc.setVisible(true);
    }//GEN-LAST:event_AccountFileMenuActionPerformed

    private void DepositMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositMenuActionPerformed
        // TODO add your handling code here:
        Deposit depo;
        depo = new Deposit();

        MainDesktop.add(depo);
        depo.setVisible(true);
    }//GEN-LAST:event_DepositMenuActionPerformed

    private void WithdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawMenuActionPerformed
        // TODO add your handling code here:
        Withdraw wd;
        wd = new Withdraw();

        MainDesktop.add(wd);
        wd.setVisible(true);
    }//GEN-LAST:event_WithdrawMenuActionPerformed

    private void AcctoAccMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcctoAccMenuActionPerformed
        // TODO add your handling code here:
        Transfer tf;
        tf = new Transfer();

        MainDesktop.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_AcctoAccMenuActionPerformed

    private void CustomerReportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerReportMenuActionPerformed
        // TODO add your handling code here:
        CustomerReport cr;
        cr = new CustomerReport();

        MainDesktop.add(cr);
        cr.setVisible(true);
    }//GEN-LAST:event_CustomerReportMenuActionPerformed

    private void CheckBalanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBalanceMenuActionPerformed
        // TODO add your handling code here:
        Balance bc;
        bc = new Balance();

        MainDesktop.add(bc);
        bc.setVisible(true);
    }//GEN-LAST:event_CheckBalanceMenuActionPerformed

    private void UserAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserAccountMenuActionPerformed
        // TODO add your handling code here:
        UserAccount uacc;
        uacc = new UserAccount();

        MainDesktop.add(uacc);
        uacc.setVisible(true);
    }//GEN-LAST:event_UserAccountMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AccountFileMenu;
    private javax.swing.JMenu AccountMenu;
    private javax.swing.JMenuItem AcctoAccMenu;
    private javax.swing.JMenu BalanceMenu;
    private javax.swing.JMenuItem CheckBalanceMenu;
    private javax.swing.JMenuItem CustomerMenu;
    private javax.swing.JMenuItem CustomerReportMenu;
    private javax.swing.JMenuItem DepositMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JDesktopPane MainDesktop;
    private javax.swing.JMenuBar MainDesktopMenuBar;
    private javax.swing.JMenu ReportMenu;
    private javax.swing.JMenu TransactionMenu;
    private javax.swing.JMenu TransferMenu;
    private javax.swing.JMenuItem UserAccountMenu;
    private javax.swing.JMenuItem WithdrawMenu;
    // End of variables declaration//GEN-END:variables
}
