/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankOfDioAditya;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dio Aditya Putra Wardhono
 */
public class Withdraw extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Deposit
     */
    public Withdraw() {
        initComponents();
        setDateNow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private Connection conn;
    private PreparedStatement insert;
    private PreparedStatement update;
    private ResultSet rs;

    /**
     *
     */
    public void setDateNow() {

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime date = LocalDateTime.now();
        String dateInString = dtf.format(date);
        DateValue.setText(dateInString);

    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        AccountNoPanel = new javax.swing.JPanel();
        AccountNoLabel = new javax.swing.JLabel();
        AccountNoTextField = new javax.swing.JTextField();
        FindButton = new javax.swing.JButton();
        WithdrawTitleLabel = new javax.swing.JLabel();
        CustomerNoLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        CustomerNoValue = new javax.swing.JLabel();
        FirstNameValue = new javax.swing.JLabel();
        LastNameValue = new javax.swing.JLabel();
        DateValue = new javax.swing.JLabel();
        BalanceLabel = new javax.swing.JLabel();
        BalanceValue = new javax.swing.JLabel();
        WithdrawLabel = new javax.swing.JLabel();
        WithdrawTextField = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        AccountNoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Account No."));

        AccountNoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AccountNoLabel.setText("Enter Account No.");

        FindButton.setText("Find");
        FindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountNoPanelLayout = new javax.swing.GroupLayout(AccountNoPanel);
        AccountNoPanel.setLayout(AccountNoPanelLayout);
        AccountNoPanelLayout.setHorizontalGroup(
            AccountNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountNoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AccountNoLabel)
                .addGap(18, 18, 18)
                .addGroup(AccountNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindButton)
                    .addComponent(AccountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        AccountNoPanelLayout.setVerticalGroup(
            AccountNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountNoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(AccountNoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(FindButton)
                .addContainerGap())
        );

        WithdrawTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        WithdrawTitleLabel.setText("Bank of Dio Aditya");

        CustomerNoLabel.setText("Customer No.");

        FirstNameLabel.setText("First Name");

        LastNameLabel.setText("Last Name");

        DateLabel.setText("Date");

        CustomerNoValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        FirstNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        LastNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        DateValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateValue.setText("jLabel8");

        BalanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BalanceLabel.setText("Balance");

        BalanceValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        WithdrawLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        WithdrawLabel.setText("Withdraw");

        WithdrawTextField.setBackground(new java.awt.Color(0, 0, 102));
        WithdrawTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        WithdrawTextField.setForeground(new java.awt.Color(255, 255, 255));

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WithdrawTitleLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccountNoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerNoLabel)
                                    .addComponent(FirstNameLabel)
                                    .addComponent(LastNameLabel))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameValue)
                                    .addComponent(FirstNameValue)
                                    .addComponent(CustomerNoValue))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WithdrawLabel)
                                    .addComponent(BalanceLabel)
                                    .addComponent(BalanceValue))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(OKButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CancelButton))
                                    .addComponent(WithdrawTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DateLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(DateValue)))
                                .addGap(89, 89, 89))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawTitleLabel)
                    .addComponent(DateLabel)
                    .addComponent(DateValue))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BalanceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(BalanceValue))
                    .addComponent(AccountNoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(WithdrawLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerNoLabel)
                            .addComponent(CustomerNoValue))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameLabel)
                            .addComponent(FirstNameValue))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel)
                            .addComponent(LastNameValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WithdrawTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OKButton)
                            .addComponent(CancelButton))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        try {
            // TODO add your handling code here:
            String account_id = AccountNoTextField.getText();
            String customer_id = CustomerNoValue.getText();
            String date = DateValue.getText();
            String balance = BalanceValue.getText();
            String withdraw = WithdrawTextField.getText();

            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", ""
            ));
            getConn().setAutoCommit(false);
            setInsert(getConn().prepareStatement(
                    "insert into withdraw(account_id,customer_id,date"
                    + ",balance,withdraw_amount)values(?,?,?,?,?)"
            ));
            getInsert().setString(1, account_id);
            getInsert().setString(2, customer_id);
            getInsert().setString(3, date);
            getInsert().setString(4, balance);
            getInsert().setString(5, withdraw);
            getInsert().executeUpdate();

            setUpdate(getConn().prepareStatement(
                    "update account set balance "
                    + "= balance - ? where account_id = ?"
            ));
            getUpdate().setString(1, withdraw);
            getUpdate().setString(2, account_id);
            getUpdate().executeUpdate();

            JOptionPane.showMessageDialog(this, "Withdraw has been Made");
            getConn().commit();

            AccountNoTextField.setText("");
            CustomerNoValue.setText("");
            FirstNameValue.setText("");
            LastNameValue.setText("");
            DateValue.setText("");
            BalanceValue.setText("");
            WithdrawTextField.setText("");

            setDateNow();
            AccountNoTextField.requestFocus();
        } catch (SQLException ex) {
            try {
                getConn().rollback();
                Logger.getLogger(Withdraw.class.getName()).log(
                        Level.SEVERE, null, ex
                );
            } catch (SQLException ex1) {
                Logger.getLogger(Withdraw.class.getName()).log(
                        Level.SEVERE, null, ex1
                );
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
        try {
            // TODO add your handling code here:
            String account_no = AccountNoTextField.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            setConn(DriverManager.getConnection(
                    "jdbc:mysql://localhost/bank_of_dio_aditya", "root", ""
            ));
            setInsert(getConn().prepareStatement(
                    "select c.customer_id, c.firstname,c.lastname, a.balance "
                    + "from customer c, account a "
                    + "where c.customer_id = a.customer_id "
                    + "and a.account_id = ?"));
            getInsert().setString(1, account_no);
            setRs(getInsert().executeQuery());

            if (getRs().next() == false) {
                JOptionPane.showMessageDialog(this, "Account not Found");
            } else {
                String customer_id = getRs().getString(1);
                String firstname = getRs().getString(2);
                String lastname = getRs().getString(3);
                String balance = getRs().getString(4);

                CustomerNoValue.setText(customer_id.trim());
                FirstNameValue.setText(firstname.trim());
                LastNameValue.setText(lastname.trim());
                BalanceValue.setText(balance.trim());
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(
                    Level.SEVERE, null, ex
            );
        }

    }//GEN-LAST:event_FindButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountNoLabel;
    private javax.swing.JPanel AccountNoPanel;
    private javax.swing.JTextField AccountNoTextField;
    private javax.swing.JLabel BalanceLabel;
    private javax.swing.JLabel BalanceValue;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CustomerNoLabel;
    private javax.swing.JLabel CustomerNoValue;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DateValue;
    private javax.swing.JButton FindButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel FirstNameValue;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LastNameValue;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel WithdrawLabel;
    private javax.swing.JTextField WithdrawTextField;
    private javax.swing.JLabel WithdrawTitleLabel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }

    /**
     * @param conn the conn to set
     */
    public void setConn(Connection conn) {
        this.conn = conn;
    }

    /**
     * @return the insert
     */
    public PreparedStatement getInsert() {
        return insert;
    }

    /**
     * @param insert the insert to set
     */
    public void setInsert(PreparedStatement insert) {
        this.insert = insert;
    }

    /**
     * @return the update
     */
    public PreparedStatement getUpdate() {
        return update;
    }

    /**
     * @param update the update to set
     */
    public void setUpdate(PreparedStatement update) {
        this.update = update;
    }

    /**
     * @return the rs
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * @param rs the rs to set
     */
    public void setRs(ResultSet rs) {
        this.rs = rs;
    }
}
